import {sanitize} from './config.js';
import {CloudSeaRenderer} from './cloud-sea.js';
import {PondSimulation} from './simulation.js';
import {PondRenderer} from './renderer.js';
import {calendarInfo} from './calendar.js';
import {PondAudio} from './audio.js';
import {WaterSurface} from './water-surface.js';
const controls=new URLSearchParams(location.search).get('surface')==='settings';
document.body.classList.toggle('controls-surface',controls);
let stored;try{stored=JSON.parse(localStorage.getItem('zen-settings-v1'));}catch{}let config=sanitize(stored);
const $=id=>document.getElementById(id),host=window.zenHost||window.chrome?.webview,native=!!host;const sim=new PondSimulation(innerWidth,innerHeight,config);let renderer=null,cloudRenderer=null;const audio=new PondAudio();let toastTimer;
function ensureScene(){
  document.body.dataset.scene=config.scene;$('clouds').hidden=config.scene!=='clouds';$('pond').setAttribute('aria-label',config.scene==='clouds'?'云海动态壁纸，双击切换桌面图标':'赏鱼壁纸，单击投喂，双击切换桌面图标');
  if(controls)return;
  if(config.scene==='clouds'&&!cloudRenderer)try{cloudRenderer=new CloudSeaRenderer($('clouds'),cloudFailure);cloudRenderer.resize(innerWidth,innerHeight);}catch(error){toast('云海需要 WebGL 2 支持：'+error.message);config.scene='pond';ensureScene();}
  if(config.scene==='pond'&&!renderer){renderer=new PondRenderer($('fish'));renderer.resize(innerWidth,innerHeight);try{renderer.waterSurface=new WaterSurface($('water'),$('fish'),message=>{$('status').textContent=message;});renderer.waterSurface.resize(innerWidth,innerHeight);}catch(error){$('water').style.display='none';document.body.dataset.waterEngine='canvas-fallback';$('status').textContent=error.message+'，使用兼容水面';}}
}
function cloudFailure(message){const failed=cloudRenderer;cloudRenderer=null;failed?.dispose();$('clouds').replaceWith($('clouds').cloneNode(false));config.scene='pond';save();refresh();toast(message);}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2600);}
function send(type,data={}){if(native)host.postMessage({type,...data});}
function save(){try{localStorage.setItem('zen-settings-v1',JSON.stringify(config));}catch{toast('无法保存设置，请检查磁盘空间');}sim.configure(config);ensureScene();send('settings',{config});}
function updateAudio(){if(!controls)audio.start(config).catch(e=>toast(e.message));}
function refresh(){ensureScene();$('pond-options').hidden=config.scene!=='pond';$('cloud-options').hidden=config.scene!=='clouds';$('scene-hint').textContent=config.scene==='clouds'?'云海流动 · 双击切换图标':'单击投喂 · 双击切换图标';$('cloud-realtime').setAttribute('aria-pressed',config.cloudMode==='realtime');$('cloud-fixed').setAttribute('aria-pressed',config.cloudMode==='fixed');$('cloud-fixed-options').hidden=config.cloudMode!=='fixed';$('cloud-clock-note').hidden=config.cloudMode==='fixed';$('cloud-time').value=config.cloudTime;$('cloud-time-value').textContent=config.cloudTime;document.querySelectorAll('[data-cloud-time]').forEach(b=>b.setAttribute('aria-pressed',config.cloudMode==='fixed'&&b.dataset.cloudTime===config.cloudTime));document.querySelectorAll('[data-scene]').forEach(b=>{const active=b.dataset.scene===config.scene;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});for(const id of ['count','speed','volume'])$(id).value=config[id];$('count-value').textContent=config.count+' 尾';$('speed-value').textContent=config.speed.toFixed(1)+' ×';$('volume-value').textContent=config.volume+' %';$('sound').checked=config.sound;$('icons').checked=config.icons;$('rain').checked=!!config.rain;$('show-calendar').checked=config.calendar;$('calendar').hidden=!config.calendar;document.body.classList.toggle('calendar-off',!config.calendar);document.querySelectorAll('[data-species]').forEach(b=>{const active=config.species.includes(b.dataset.species);b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});}
for(const [name,color,id] of [['红白','#c27a62','kohaku'],['黄金','#d7bc78','yamabuki'],['三色','#bacaba','sanke'],['纯红','#bd342e','benigoi']]){const b=document.createElement('button');b.dataset.species=id;b.innerHTML=`<i class="swatch" style="background:${color}"></i>${name}`;b.onclick=()=>{if(config.species.includes(id)){if(config.species.length===2){toast('保留至少两种鱼，水面更有层次');return;}config.species=config.species.filter(x=>x!==id);}else {if(config.species.length>=3){toast('最多选择三种鱼，请先取消一种');return;}config.species.push(id);}save();refresh();};$('species').append(b);}
for(const [id,name,ready] of [['pond','赏鱼',true],['clouds','云海',true],['rain','听雨',false],['ocean','观海听涛',false],['forest','林海雪原',false],['bamboo','竹林幽径',false]]){const b=document.createElement('button');b.className='scene';b.dataset.scene=id;b.disabled=!ready;b.innerHTML=name+(id==='clouds'?'<small class="beta">Beta</small>':ready?'':'<small>待实现</small>');if(ready)b.onclick=()=>{clearTimeout(clickTimer);config.scene=id;save();refresh();};$('scenes').append(b);}
for(const mode of ['realtime','fixed'])$('cloud-'+mode).onclick=()=>{config.cloudMode=mode;save();refresh();};
$('cloud-time').onchange=()=>{config.cloudTime=$('cloud-time').value;config=sanitize(config);save();refresh();};
for(const b of document.querySelectorAll('[data-cloud-time]'))b.onclick=()=>{config.cloudTime=b.dataset.cloudTime;save();refresh();};
for(const id of ['count','speed','volume'])$(id).oninput=()=>{config[id]=Number($(id).value);save();refresh();if(id==='volume')updateAudio();};
$('show-calendar').onchange=()=>{config.calendar=$('show-calendar').checked;save();refresh();};
$('rain').onchange=()=>{config.rain=$('rain').checked;save();refresh();};
function settingsTab(name){for(const n of ['wallpaper','software']){const active=n===name;$(`${n}-options`).hidden=!active;$(`${n}-tab`).setAttribute('aria-selected',active);$(`${n}-tab`).tabIndex=active?0:-1;}}
for(const n of ['wallpaper','software']){const b=$(`${n}-tab`);b.onclick=()=>settingsTab(n);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'wallpaper':e.key==='End'?'software':n==='wallpaper'?'software':'wallpaper';settingsTab(next);$(`${next}-tab`).focus();}};}
$('sound').onchange=()=>{config.sound=$('sound').checked;save();updateAudio();};$('icons').onchange=()=>{config.icons=$('icons').checked;save();send('icons',{hidden:config.icons});if(!native)toast('浏览器预览无法改变 Windows 桌面图标');};
let panelTimer;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
function openSettings(){if(native&&!controls){send('openSettings');return;}clearTimeout(panelTimer);$('settings').hidden=false;$('settings-button').disabled=true;$('settings-button').classList.add('button-away');requestAnimationFrame(()=>requestAnimationFrame(()=>$('settings').classList.add('panel-open')));$('close').focus();}
function closeSettings(){clearTimeout(panelTimer);$('settings').classList.remove('panel-open');$('settings-button').disabled=false;$('settings-button').classList.remove('button-away');panelTimer=setTimeout(()=>{$('settings').hidden=true;$('settings-button').focus();send('panel',{open:false});},reducedMotion.matches?0:360);}
$('settings-button').onclick=openSettings;$('close').onclick=closeSettings;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSettings();});
let clickTimer=null;$('pond').addEventListener('click',e=>{if(e.detail>1)return;const x=e.clientX,y=e.clientY;clearTimeout(clickTimer);clickTimer=setTimeout(()=>{if(config.scene==='pond')sim.feed(x,y);if(config.sound)updateAudio();},native?GetDoubleClickDelay():280);});
function GetDoubleClickDelay(){return window.zenDoubleClickTime||500;}
$('pond').addEventListener('dblclick',()=>{clearTimeout(clickTimer);config.icons=!config.icons;save();refresh();send('icons',{hidden:config.icons});toast(native?(config.icons?'桌面图标已隐藏':'桌面图标已显示'):'双击已识别，桌面图标切换仅在 Windows 程序中生效');});
$('quit').onclick=()=>{if(native)send('quit');else toast('浏览器预览中请关闭此标签页');};
let db;const dbReady=new Promise(resolve=>{const req=indexedDB.open('zen-media',1);req.onupgradeneeded=()=>req.result.createObjectStore('music');req.onsuccess=()=>{db=req.result;resolve(db);};req.onerror=()=>resolve(null);});
async function mediaStore(action,value){await dbReady;if(!db)return;return new Promise((resolve,reject)=>{const tx=db.transaction('music',action==='get'?'readonly':'readwrite'),s=tx.objectStore('music');const q=action==='get'?s.get('custom'):action==='delete'?s.delete('custom'):s.put(value,'custom');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
async function loadMusic(){const record=await mediaStore('get');if(record){if(!controls)audio.replace(record.blob);$('music-name').textContent=record.name;}else{audio.restore();$('music-name').textContent='未选择音乐';}updateAudio();}
loadMusic().catch(()=>{});
$('replace-music').onclick=()=>$('music-file').click();$('music-file').onchange=async()=>{const f=$('music-file').files[0];if(!f)return;if(f.size>100*1024*1024){toast('请选择小于 100 MB 的音乐文件');return;}if(!controls)audio.replace(f);$('music-name').textContent=f.name;try{await mediaStore('put',{blob:f,name:f.name});send('musicChanged');}catch{toast('音乐已加载，但未能保存');}updateAudio();$('music-file').value='';};
$('restore-music').onclick=async()=>{audio.restore();$('music-name').textContent='未选择音乐';await mediaStore('delete');send('musicChanged');toast('已移除自定义音乐');};
function calendar(){const info=calendarInfo();$('solar').textContent=info.solar;$('lunar').textContent=info.lunar;const n=info.next;$('countdown').innerHTML=n?(n.days===0?`今日 · ${n.name}`:`距 ${n.name} 还有 <strong>${n.days}</strong> 天`):'';}calendar();setInterval(calendar,60000);
function resize(){sim.resize(innerWidth,innerHeight);renderer?.resize(innerWidth,innerHeight);renderer?.waterSurface?.resize(innerWidth,innerHeight);cloudRenderer?.resize(innerWidth,innerHeight);}addEventListener('resize',resize);resize();refresh();
let lastRAF=performance.now(),previous=lastRAF,heartbeat=0,frameCount=0,profileStart=previous,cpuTotal=0;let profile={fps:0,cpuMs:0};function drawFrame(now){const dt=Math.min((now-previous)/1000,.05);previous=now;if((native&&!controls)||!document.hidden){const renderStart=performance.now();if(config.scene==='clouds')cloudRenderer?.render(config,dt);else{sim.update(dt);renderer?.render(sim,dt);}cpuTotal+=performance.now()-renderStart;frameCount++;if(now-profileStart>=2000){profile={fps:frameCount*1000/(now-profileStart),cpuMs:cpuTotal/frameCount};frameCount=0;cpuTotal=0;profileStart=now;}if(native&&now-heartbeat>2000){heartbeat=now;send('rendered',{engine:config.scene==='clouds'?'takram-clouds-webgl':document.body.dataset.waterEngine||'initializing',frames:config.scene==='clouds'?(cloudRenderer?.frames||0):(renderer?.waterSurface?.steps||0),panelOpen:!$('settings').hidden,simulationTime:sim.time,pageVisibility:document.visibilityState});}}}function frame(now){lastRAF=now;drawFrame(now);requestAnimationFrame(frame);}if(!controls)requestAnimationFrame(frame);
document.addEventListener('visibilitychange',()=>{if(native&&!controls)return;if(document.hidden)audio.stop();else if(config.sound)updateAudio();});
if(native){host.addEventListener('message',e=>{const m=e.data;if(m.type==='frameTick'){const now=performance.now();if(!controls&&now-lastRAF>100&&now-previous>=m.interval*.8)drawFrame(now);return;}if(m.type==='status'){$('status').textContent=m.message;}if(m.type==='openSettings')openSettings();if(m.type==='closeSettings')closeSettings();if(m.type==='config'){config=sanitize(m.config);sim.configure(config);refresh();updateAudio();}if(m.type==='musicChanged')loadMusic().catch(()=>toast('音乐读取失败'));if(m.type==='icons'){config.icons=m.hidden;save();refresh();}if(m.type==='feed'&&config.scene==='pond')sim.feed(m.normalized?m.x*innerWidth:m.x,m.normalized?m.y*innerHeight:m.y);if(m.type==='doubleClick'){config.icons=m.hidden;save();refresh();}if(m.type==='doubleClickTime')window.zenDoubleClickTime=m.value;if(m.type==='desktopHover'){$('calendar').classList.toggle('desktop-hover',m.calendar);$('settings-button').classList.toggle('desktop-hover',m.settings);}});send('ready',{config});}else $('status').textContent='浏览器预览 · 桌面挂载和图标控制请运行 Windows 程序';
if(controls)openSettings();
// Read-only diagnostics used by smoke tests and profiling.
window.zenDiagnostics=()=>({scene:config.scene,cloud:cloudRenderer?{...cloudRenderer.clock,elapsed:cloudRenderer.elapsed,frames:cloudRenderer.frames,ready:cloudRenderer.ready,engine:'takram-webgl',gpuMs:cloudRenderer.gpuMs,renderSize:{width:cloudRenderer.canvas.width,height:cloudRenderer.canvas.height},error:cloudRenderer.error||null}:null,profile,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},foodState:sim.food.map(f=>({x:f.x,y:f.y})),fish:sim.fish.length,food:sim.food.length,eaten:sim.eaten,rainDrops:sim.rainDrops.length,species:[...new Set(sim.fish.map(f=>f.species))],config:{...config},time:sim.time,activeDarts:sim.fish.filter(f=>f.dartAge>=0).length,fishState:sim.fish.map(f=>({x:f.x,y:f.y,speed:f.velocity,angle:f.angle,curvature:f.curvature,kick:f.kickAge,dart:f.dartAge}))});
