import {PondSimulation} from './simulation.js';
import {PondRenderer} from './renderer.js';
import {calendarInfo} from './calendar.js';
import {PondAudio} from './audio.js';
import {WaterSurface} from './water-surface.js';
const controls=new URLSearchParams(location.search).get('surface')==='settings';
document.body.classList.toggle('controls-surface',controls);
const defaults={count:16,speed:.8,species:['kohaku','yamabuki','sanke'],rain:false,sound:false,volume:35,icons:true,calendar:true};
function sanitize(value){const v={...defaults,...value};v.count=Math.max(6,Math.min(32,Number(v.count)||16));v.speed=Math.max(.4,Math.min(1.8,Number(v.speed)||.8));v.volume=Math.max(0,Math.min(100,Number(v.volume)||0));v.species=[...new Set((Array.isArray(v.species)?v.species:[]).filter(x=>defaults.species.includes(x)))];if(v.species.length<2)v.species=[...defaults.species];delete v.fps;v.sound=!!v.sound;v.icons=!!v.icons;v.calendar=v.calendar!==false;return v;}
let stored;try{stored=JSON.parse(localStorage.getItem('zen-settings-v1'));}catch{}let config=sanitize(stored);
const $=id=>document.getElementById(id),host=window.zenHost||window.chrome?.webview,native=!!host;const sim=new PondSimulation(innerWidth,innerHeight,config);const renderer=controls?null:new PondRenderer($('fish'));const audio=new PondAudio();let toastTimer;
if(renderer)try{renderer.waterSurface=new WaterSurface($('water'),$('fish'),message=>{$('status').textContent=message;});}catch(error){$('water').style.display='none';document.body.dataset.waterEngine='canvas-fallback';$('status').textContent=error.message+'，使用兼容水面';}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2600);}
function send(type,data={}){if(native)host.postMessage({type,...data});}
function save(){try{localStorage.setItem('zen-settings-v1',JSON.stringify(config));}catch{toast('无法保存设置，请检查磁盘空间');}sim.configure(config);send('settings',{config});}
function updateAudio(){if(!controls)audio.start(config).catch(e=>toast(e.message));}
function refresh(){for(const id of ['count','speed','volume'])$(id).value=config[id];$('count-value').textContent=config.count+' 尾';$('speed-value').textContent=config.speed.toFixed(1)+' ×';$('volume-value').textContent=config.volume+' %';$('sound').checked=config.sound;$('icons').checked=config.icons;$('rain').checked=!!config.rain;$('show-calendar').checked=config.calendar;$('calendar').hidden=!config.calendar;document.body.classList.toggle('calendar-off',!config.calendar);document.querySelectorAll('[data-species]').forEach(b=>{const active=config.species.includes(b.dataset.species);b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});}
for(const [name,color,id] of [['红白','#c27a62','kohaku'],['黄金','#d7bc78','yamabuki'],['三色','#bacaba','sanke']]){const b=document.createElement('button');b.dataset.species=id;b.innerHTML=`<i class="swatch" style="background:${color}"></i>${name}`;b.onclick=()=>{if(config.species.includes(id)){if(config.species.length===2){toast('保留至少两种鱼，水面更有层次');return;}config.species=config.species.filter(x=>x!==id);}else config.species.push(id);save();refresh();};$('species').append(b);}
for(const [name,ready] of [['赏鱼',true],['听雨',false],['观海听涛',false],['林海雪原',false],['竹林幽径',false]]){const b=document.createElement('button');b.className='scene'+(ready?' active':'');b.disabled=!ready;b.innerHTML=name+(ready?'':'<small>待实现</small>');if(ready)b.setAttribute('aria-pressed','true');$('scenes').append(b);}
for(const id of ['count','speed','volume'])$(id).oninput=()=>{config[id]=Number($(id).value);save();refresh();if(id==='volume')updateAudio();};
$('show-calendar').onchange=()=>{config.calendar=$('show-calendar').checked;save();refresh();};
$('rain').onchange=()=>{config.rain=$('rain').checked;save();refresh();};
function settingsTab(name){for(const n of ['wallpaper','software']){const active=n===name;$(`${n}-options`).hidden=!active;$(`${n}-tab`).setAttribute('aria-selected',active);$(`${n}-tab`).tabIndex=active?0:-1;}}
for(const n of ['wallpaper','software']){const b=$(`${n}-tab`);b.onclick=()=>settingsTab(n);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'wallpaper':e.key==='End'?'software':n==='wallpaper'?'software':'wallpaper';settingsTab(next);$(`${next}-tab`).focus();}};}
$('sound').onchange=()=>{config.sound=$('sound').checked;save();updateAudio();};$('icons').onchange=()=>{config.icons=$('icons').checked;save();send('icons',{hidden:config.icons});if(!native)toast('浏览器预览无法改变 Windows 桌面图标');};
let panelTimer;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
function openSettings(){if(native&&!controls){send('openSettings');return;}clearTimeout(panelTimer);$('settings').hidden=false;$('settings-button').disabled=true;$('settings-button').classList.add('button-away');requestAnimationFrame(()=>requestAnimationFrame(()=>$('settings').classList.add('panel-open')));$('close').focus();}
function closeSettings(){clearTimeout(panelTimer);$('settings').classList.remove('panel-open');$('settings-button').disabled=false;$('settings-button').classList.remove('button-away');panelTimer=setTimeout(()=>{$('settings').hidden=true;$('settings-button').focus();send('panel',{open:false});},reducedMotion.matches?0:360);}
$('settings-button').onclick=openSettings;$('close').onclick=closeSettings;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSettings();});
let clickTimer=null;$('pond').addEventListener('click',e=>{if(e.detail>1)return;const x=e.clientX,y=e.clientY;clearTimeout(clickTimer);clickTimer=setTimeout(()=>{sim.feed(x,y);if(config.sound)updateAudio();},native?GetDoubleClickDelay():280);});
function GetDoubleClickDelay(){return window.zenDoubleClickTime||500;}
$('pond').addEventListener('dblclick',()=>{clearTimeout(clickTimer);config.icons=!config.icons;save();refresh();send('icons',{hidden:config.icons});toast(native?(config.icons?'桌面图标已隐藏':'桌面图标已显示'):'双击已识别，桌面图标切换仅在 Windows 程序中生效');});
$('quit').onclick=()=>{if(native)send('quit');else toast('浏览器预览中请关闭此标签页');};
let db;const dbReady=new Promise(resolve=>{const req=indexedDB.open('zen-media',1);req.onupgradeneeded=()=>req.result.createObjectStore('music');req.onsuccess=()=>{db=req.result;resolve(db);};req.onerror=()=>resolve(null);});
async function mediaStore(action,value){await dbReady;if(!db)return;return new Promise((resolve,reject)=>{const tx=db.transaction('music',action==='get'?'readonly':'readwrite'),s=tx.objectStore('music');const q=action==='get'?s.get('custom'):action==='delete'?s.delete('custom'):s.put(value,'custom');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
async function loadMusic(){const record=await mediaStore('get');if(record){if(!controls)audio.replace(record.blob);$('music-name').textContent=record.name;}else{audio.restore();$('music-name').textContent='未选择音乐';}updateAudio();}
loadMusic().catch(()=>{});
$('replace-music').onclick=()=>$('music-file').click();$('music-file').onchange=async()=>{const f=$('music-file').files[0];if(!f)return;if(f.size>100*1024*1024){toast('请选择小于 100 MB 的音乐文件');return;}if(!controls)audio.replace(f);$('music-name').textContent=f.name;try{await mediaStore('put',{blob:f,name:f.name});send('musicChanged');}catch{toast('音乐已加载，但未能保存');}updateAudio();$('music-file').value='';};
$('restore-music').onclick=async()=>{audio.restore();$('music-name').textContent='未选择音乐';await mediaStore('delete');send('musicChanged');toast('已移除自定义音乐');};
function calendar(){const info=calendarInfo();$('solar').textContent=info.solar;$('lunar').textContent=info.lunar;const n=info.next;$('countdown').innerHTML=n?(n.days===0?`今日 · ${n.name}`:`距 ${n.name} 还有 <strong>${n.days}</strong> 天`):'';}calendar();setInterval(calendar,60000);
function resize(){if(!renderer)return;sim.resize(innerWidth,innerHeight);renderer.resize(innerWidth,innerHeight);renderer.waterSurface?.resize(innerWidth,innerHeight);}addEventListener('resize',resize);resize();refresh();
let lastRAF=performance.now(),previous=lastRAF,heartbeat=0,frameCount=0,profileStart=previous,cpuTotal=0;let profile={fps:0,cpuMs:0};function drawFrame(now){const dt=Math.min((now-previous)/1000,.05);previous=now;if((native&&!controls)||!document.hidden){const renderStart=performance.now();sim.update(dt);renderer.render(sim,dt);cpuTotal+=performance.now()-renderStart;frameCount++;if(now-profileStart>=2000){profile={fps:frameCount*1000/(now-profileStart),cpuMs:cpuTotal/frameCount};frameCount=0;cpuTotal=0;profileStart=now;}if(native&&now-heartbeat>2000){heartbeat=now;send('rendered',{engine:document.body.dataset.waterEngine||'initializing',frames:renderer.waterSurface?.steps||0,panelOpen:!$('settings').hidden,simulationTime:sim.time,pageVisibility:document.visibilityState});}}}function frame(now){lastRAF=now;drawFrame(now);requestAnimationFrame(frame);}if(!controls)requestAnimationFrame(frame);
document.addEventListener('visibilitychange',()=>{if(native&&!controls)return;if(document.hidden)audio.stop();else if(config.sound)updateAudio();});
if(native){host.addEventListener('message',e=>{const m=e.data;if(m.type==='frameTick'){const now=performance.now();if(!controls&&now-lastRAF>100&&now-previous>=m.interval*.8)drawFrame(now);return;}if(m.type==='status'){$('status').textContent=m.message;}if(m.type==='openSettings')openSettings();if(m.type==='closeSettings')closeSettings();if(m.type==='config'){config=sanitize(m.config);sim.configure(config);refresh();updateAudio();}if(m.type==='musicChanged')loadMusic().catch(()=>toast('音乐读取失败'));if(m.type==='icons'){config.icons=m.hidden;save();refresh();}if(m.type==='feed')sim.feed(m.normalized?m.x*innerWidth:m.x,m.normalized?m.y*innerHeight:m.y);if(m.type==='doubleClick'){config.icons=m.hidden;save();refresh();}if(m.type==='doubleClickTime')window.zenDoubleClickTime=m.value;if(m.type==='desktopHover'){$('calendar').classList.toggle('desktop-hover',m.calendar);$('settings-button').classList.toggle('desktop-hover',m.settings);}});send('ready',{config});}else $('status').textContent='浏览器预览 · 桌面挂载和图标控制请运行 Windows 程序';
if(controls)openSettings();
// Read-only diagnostics used by smoke tests and profiling.
window.zenDiagnostics=()=>({profile,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},foodState:sim.food.map(f=>({x:f.x,y:f.y})),fish:sim.fish.length,food:sim.food.length,eaten:sim.eaten,rainDrops:sim.rainDrops.length,species:[...new Set(sim.fish.map(f=>f.species))],config:{...config},time:sim.time,activeDarts:sim.fish.filter(f=>f.dartAge>=0).length,fishState:sim.fish.map(f=>({x:f.x,y:f.y,speed:f.velocity,angle:f.angle,curvature:f.curvature,kick:f.kickAge,dart:f.dartAge}))});
